buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://jcenter.bintray.com' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
