apply plugin: 'com.android.library'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        minSdkVersion 17
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters "x86", "armeabi-v7a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.3.1'

    // 仅拉取 x86 底层 C/C++ 动态库，排除 Java 类避免本地代码冲突
    implementation('tv.danmaku.ijk.media:ijkplayer-x86:0.8.8') {
        exclude group: 'tv.danmaku.ijk.media', module: 'ijkplayer-java'
    }

    // ExoPlayer 核心组件
    implementation 'com.google.android.exoplayer:exoplayer-core:2.14.2'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.14.2'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.14.2'
    implementation 'com.google.android.exoplayer:extension-rtmp:2.14.2'
}
